version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coopvoting
    cap_add:
        - SYS_NICE
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    ports:
      - 9090:9090